export const APP_MESSAGE = 'APP_MESSAGE';
export const FETCHED_APPSTORE_LIST = 'FETCHED_APPSTORE_LIST';
export const FETCHING_APPSTORE_LIST = 'FETCHING_APPSTORE_LIST';
export const SELECT_APP_TO_INSTALL = 'SELECT_APP_TO_INSTALL';
export const TOGGLE_APP_RESOURCE =  'TOGGLE_APP_RESOURCE';